const perChar = ['Honest', 'Brave', 'Compassionate', 'Leader', 'Courageous', 'Unselfish', 'Loyal', 'Hard-working', 'Independent', 'Selfish', 'Responsible', 'Considerate', 'Self-confident', 'Humble'];
const fortune = ['Beware of the blinding red light. If you see this light, you must flee. It will only bring you death!',
	'You will find the answer to a long, mysterious riddle in your family bloodline buried between two oak trees, west of the village you grew up in.',
	'A path of death lies in your wake.',
	'Greed is a poor man’s compass, and I see gold and riches in your future.',
	'A single wolf is slaughtered by many enemies that surround it. Let this be a warning sign of danger that is preventable by the pack.',
	'The truth will come from a child’s toy. The lie will come from a weapon.',
	'You must drink of the poison well and eat of the spoiled pantry.',
	'Follow the flight of birds, never in winter, always returning.',
	'A song contains a wish. Only the name will answer.',
    'The mother has disguised herself. Her babe is lost and will not return. She will nurse no other.',
	'The gears turn long after the machine has been broken. He who built it cannot mend it. He who holds it cannot carry it. He who finds it cannot speak it.',
	'Gaze through the cracked window, and only then will you see clearly.',
    'Beware the men with gills. Speak not to the sea or the southern wind.',
	'Beware the snake’s venom, not its bite.',
	'Travel five days with the silver star at your heels, then cross the raging river. There you will come to realize your true self.',
	'The light will be in the shadowest darkness.',
	'Not all the frogs are in the pond, beware of them.',
	'One for the fire, two for the clouds, and three for the knights.',
	'Don’t trust the song of the birds.',
	'Cloak in the water. The man is crying. Let the leaf falls and everything will be fine.',
	'For one wish to make, it’ll be more wish to crumble.',
	'In the high plain there’s a dark moon. Don’t follow the light.',
	'When the dawn will come at the birthday of the mother, rats and snakes will devour all hopes.',
	'Near the montains, there is a grey falcon. Look at the eyes, and you’ll die. Look at the tail, and you’ll be rich.',
	'Don’t move when the night song come, or you’ll gain something you don’t want, and lost something you wanted to keep.',
	'Today was possibly the most important day of your life! Congrat.. oh… you missed it… tsk tsk tsk… What a shame… A do-over, then! Tomorrow you will wake up and it will be today. Make sure you return or that decree will stay. k, Bye!',
	'Do not trust your thoughts. They will hinder your victory.',
	'A figment in blue will cross your path tomorrow. You will know it when you see the sign. You must turn around 4 times and speak the following words:',
	'And through the drifts the snowy clifts Did send a dismal sheen: Nor shapes of men nor beasts we ken The ice was all between.',
	'If you believe in telekinesis, raise my hand. The fortune teller then proceeds to raise their hand.',
	'When you are done, the spirit haunting will pass over you.',
	'A dragon will give you a jewel. Beware the generous miser.',
	'The path less traveled is paved in gold.',
	'Find the woman who gives birds their song.',
	'Beware, young mouse, for the lion is thorned.',
	'(Do/Do not) Cross the Mountain!',
	'(1d10) Stars Mark the Path!',
	'The Moon Shines Brightest to Those in Her Favor.',
	'Speak Not The Name Unspoken; They Listen, Always.',
	'Beware, for the Great Gyre is Nigh; The Slouching Beast Will Soon Arrive!',
	'Swords Shall Pierce Thine Heart; Pin Thy Love Lest It Be Lost.',
	'Three Crones Shall Visit Thee and Thier Lights Shall Reveal the Truth of What Thou Doth Seek!',
	'Keep a Candle Burning; Lest The Dark Take Even Your Fears Away.',
	'Build Not Houses of White Stone.',
	'Three Coins Must Ye Pay; Three Prices Dear, Secrets Thrice Revealed, ‘ere The Light of Day.',
	'Gold, Silver, Copper; Never in the Opposite Order!',
	'Spill Forth a Dram for the Lost; Make Merry in the Name of Those Who Pay the Highest Price!',
	'You Must Seek the Leaf that Grows Not On Any Tree!',
	'Jump the Broom; Dance above the Blades!',
	'Sphinx of Black Quartz, Judge Thy Vow.',
	'Seek the Egg of Stone; Face the Dragon!',
	'Your nights will grow colder still, to match the heat of growing fires.',
	'Trust the twin with no siblings, but abhor the lone child.',
	'The face of the one you seek is thus- a busker at dawn; a composer at noon; a patron at dusk; a maestro under the stars.',
	'Your money, here, have it back. The fortune you’ve asked me to read, never shall I speak of it in this life or any hereafter.',
	'A wilting lineage droops to shadowy lows. What the rotten fruit begets chokes out the tree of its birth.',
	'Beware! Blessings from above may actually be curses from below!',
	'A helping hand will come from an unlikely place. Trust it at your own peril.',
	'When the leaves fall from the trees so too shall the stars fall from the sky.',
	'The wisest men envy the grave.',
	'The poison of the moon lies only once.',
	'There be dragons in ye head. Make sure to feed them.',
	'The treasure you are looking for is in the fruit.',
	'Poorly-dresed skanks like you will die alone. Naked, and alone. (Works best in an arctic setting, or not.)',
	'Never bring upon yourself the wrath of the chicken. You may think this a metaphor, but it is not. Their beaks are sharp like my toes.',
	'Your hands will taste of orange in the near future.',
	'That which you hold most dear will turn against you and lead you to ruin',
	'Your actions have had unintended and unforeseeable consequences, and have placed into action the final piece of that which now approaches you. You are the harbinger of your own death',
	'The thoughts you have had but not put into action are leading you down a path to your own undoing',
	'The fall of slow rain upon the barren field will lead you to the house which shelters your destiny',
	'Steel your heart for darkness ahead. Your betrayal has already happened though you do not yet know it.',
	'Seek ye the good behind the bad and beware the bad behind the good.',
	'Never lick a horse in the mouth, they bite.',
	'A Fall is Coming; Winter Just Round the Bend; Enjoy Spring; Summer Shall Bring An End!',
	'Let Not Cold Enter Your Heart, For Then Only Love Can Drive It Out!',
	'The black sky will shield you from your enemies. Travel by night.',
	'The rope with which you climb may also hang you if you are not careful.',
	'You will be an old man/woman by the time your quest is complete.',
	'Fools will take great heed of your words. Use this to your advantage.',
	'A shrewd and very attractive fortune teller has put a curse on you. I will remove it for an additional sum.',
	'Trust not the travelers numbering odd.',
	'Take something old, give something new, doubt something red, trust something blue.',
	'Left at the stream, at the face look right, crawl through the dark, and you will find the light!',
	'Salt thy wounds, relish the sting, sweet is the knave, and bold is the king.',
	'Thrice will call the raven, heed its warn lest the fourth cry your dirge.',
	'Between silver and gold, choose evil’s bane. Between fire and chill, the lady’s kiss.',
	'The shadow of the dragon is an omen, but coming of the wolf is the sign.',
	'Begrudge not the thieving monkey, lest you take its place in the tiger’s jaws.',
	'Lay not your head in the barn animals’ bed, for the headsman soon calls.',
	'A copper for the maid, a silver to the beggar, and a gold for a lonely tune, may the vault of riches open to you.',
	'Someone you remember, someone you forget, someone with a favor, another with a threat.',
	'Poor fortune for ye, unless you confess your guilt to the willow tree.',
	'Your luck is a shame until you trade with your mate who has one of the same.',
	'A fortune most cold if you do as yous’re told.',
	'Torch and candle, wax and wick, in the hall of fire, move right quick!',
	'Look for the priestess, she will bring salvation.',
	'An ancient empire will rise from the waves along with ancient secrets.',
	'Only when the lovers are reunited can the curse be broken.',
	'As the hermit emerges from hiding, darkness shall soon emerge as well.',
	'Watch for a nobleman in red, for he is a devil in disguise.'];
   

	const kindness = [ 'Pay it Backward: buy coffee for the person behind you in line.',
		 'Compliment the first three people you talk to today.',
		 'Send a positive text message to five different people right now.',
		 'Post inspirational sticky notes around your neighborhood, office, school, etc.',
		 'Tell someone they dropped a dollar (even though they didn’t). Then give them a dollar.',
		 'Donate old towels or blankets to an animal shelter.',
		 'Say hi to the person next to you on the elevator.',
		 'Surprise a neighbor with freshly baked cookies or treats!',
		 'Let someone who only has a few items go in front of you in line.',
		 'Leave a gas gift card at a gas pump.',
		 'Throw a party to celebrate someone just for being who they are, which is awesome.',
		 'Have a LinkedIn account? Write a recommendation for coworker or connection.',
		 'Leave quarters at the laundromat.',
		 'Encounter someone in customer service who is especially kind? Take an extra five minutes to tell their manager.',
		 'Leave unused coupons next to corresponding products in the grocery store.',
		 'Leave a note on someone’s car telling them how awesome they parked.',
		 'Try to make sure every person in a group conversation feels included.',
		 'Write a kind message on your mirror with a dry erase marker for yourself, your significant other, or a family member.',
		 'Place a positive body image note in jean pockets at a department store.',
		 'Smile at five strangers.',
		 'Set an alarm on your phone to go off at three different times during the day. In those moments, do something kind for someone else.',
		 'Send a gratitude email to a coworker who deserves more recognition.',
		 'Practice self-kindness and spend 30 minutes doing something you love today.',
		 'Give away stuff for free on Craig’s List.',
		 'Write a gratitude list in the morning and again in the evening.',
		 'Know parents who could use a night out? Offer to babysit for free.',
		 'Hold up positive signs for traffic or in a park for people exercising outside!',
		 'Return shopping carts for people at the grocery store.',
		 'Buy a plant. Put it in a terracotta pot. Write positive words that describe a friend on the pot. Give it to that friend!',
		 'Write a positive comment on your favorite blog, website, or a friend’s social media account.',
		 'Have a clean-up party at a beach or park.',
		 'While you’re out, compliment a parent on how well-behaved their child is.',
		 'Leave a kind server the biggest tip you can afford.',
		 'When you’re throwing something away on the street, pick up any litter around you and put that in the trash too.',
		 'Pay the toll for the person behind you.',
		 'Put 50 paper hearts in a box. On each cutout write something that is special about your partner or a friend. Give them the box and tell them to pull out a heart anytime they need a pick-me-up.',
		 'Everyone is important. Learn the names of your office security guard, the person at the front desk, and other people you see every day. Greet them by name. Also say “hello” to strangers and smile. These acts of kindness are so easy and they almost always make people smile!',
		 'Write your partner a list of things you love about them.',
		 'Purchase extra dog or cat food and take it to an animal shelter.',
		 'Find opportunities to give compliments. It costs nothing, takes no time, and could make someone’s entire day. Don’t just think it. Say it.',
		 'Take flowers or treats to the nurses’ station at your nearest hospital.',
		 'Keep an extra umbrella at work so you can lend it out when it rains.',
		 'Send a ‘Thank You’ card or note to the officers at your local police or fire station.',
		 'Take muffins or cookies to your local librarians.',
		 'Run an errand for a family member who is busy.',
		 'Leave a box of goodies in your mailbox for your mail carrier.',
		 'Tape coins around a playground for kids to find.',
		 'Put your phone away while in the company of others.',
		 'Email or write to a former teacher who made a difference in your life.',
		 'When you hear that discouraging voice in your head, tell yourself something positive. You deserve kindness too!']
	 

function generateMessage() {
	const yourChar = Math.floor(Math.random() * perChar.length);
	const yourFortune = Math.floor(Math.random() * fortune.length);
	const yourKindness = Math.floor(Math.random() * kindness.length);

	console.log(yourChar);
	console.log(yourFortune);
	console.log(yourKindness);

console.log(perChar[yourChar]);
console.log(fortune[yourFortune]);
console.log(kindness[yourKindness]);
};
